global:
  scrape_interval: 15s 

rule_files:
  - "alert_rules.yml" # Alerts ki logic yahan hogi

scrape_configs:
  - job_name: 'fraud-detection-api'
    static_configs:
      - targets: ['localhost:8000'] # Aapka Model API endpoint

  - job_name: 'vertex-ai-metrics'
    static_configs:
      - targets: ['monitoring.googleapis.com']
